#!/usr/bin/env python3
"""Scan the pinned 25-repo corpus and write per-repo/per-rule/per-severity counts.

Every finding this produces must be hand-triaged into
tests/benchmark/corpus-triage.json. A corpus count with no triage behind it
is the same defect as a benchmark score with no detector behind it.

Usage:
    python scripts/corpus_scan.py --corpus-dir /path/to/checkouts
    python scripts/corpus_scan.py --corpus-dir DIR --out tests/benchmark/corpus-results.json
"""

from __future__ import annotations

import argparse
import json
import os
import sys
import time
from collections import defaultdict
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

from actenon_scan.engine import scan_path_parallel  # noqa: E402

PINNED = REPO_ROOT / "tests" / "benchmark" / "pinned_repos.json"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--corpus-dir", required=True, type=Path)
    ap.add_argument("--out", type=Path, default=REPO_ROOT / "tests/benchmark/corpus-results.json")
    ap.add_argument("--jobs", type=int, default=os.cpu_count() or 4)
    args = ap.parse_args()

    pinned = json.loads(PINNED.read_text())
    results: dict[str, object] = {}
    all_findings: list[dict] = []
    totals: dict[str, int] = defaultdict(int)

    for entry in pinned["repos"]:
        name = entry["name"]
        path = args.corpus_dir / name
        if not path.exists():
            print(f"MISSING  {name}: {path}", file=sys.stderr)
            results[name] = {"error": "not fetched"}
            continue

        t = time.perf_counter()
        res = scan_path_parallel(path, jobs=args.jobs)
        elapsed = (time.perf_counter() - t) * 1000

        active = [f for f in res.findings if not f.suppressed]
        by_rule: dict[str, int] = defaultdict(int)
        by_sev: dict[str, int] = defaultdict(int)
        for f in active:
            by_rule[f.rule_id] += 1
            by_sev[f.effective_severity if hasattr(f, "effective_severity") else f.severity] += 1
            all_findings.append({
                "repo": entry["repo"],
                "name": name,
                "category": entry["category"],
                "sha": entry["sha"],
                "file": f.file,
                "line": f.line,
                "rule_id": f.rule_id,
                "severity": f.severity,
                "confidence": getattr(f, "confidence", "?"),
                "description": f.description,
                "call_text": getattr(f, "call_text", ""),
            })

        results[name] = {
            "repo": entry["repo"],
            "category": entry["category"],
            "sha": entry["sha"],
            "files_scanned": res.files_scanned,
            "ms": round(elapsed),
            "findings": len(active),
            "by_rule": dict(sorted(by_rule.items())),
            "by_severity": dict(sorted(by_sev.items())),
            "analysis_errors": len(res.analysis_errors),
            "unsupported_files": len(res.unsupported_files),
        }
        totals[entry["category"]] += len(active)
        flag = "  <-- CONTROL REPO" if entry["category"] == "control" and active else ""
        print(f"{name:22} {entry['category']:12} files={res.files_scanned:6} "
              f"findings={len(active):4} {round(elapsed):6}ms{flag}")

    doc = {
        "_comment": "Generated by scripts/corpus_scan.py. Every finding here must have a "
                    "hand-triaged entry in corpus-triage.json.",
        "totals_by_category": dict(totals),
        "total_findings": len(all_findings),
        "repos": results,
        "findings": all_findings,
    }
    args.out.write_text(json.dumps(doc, indent=2) + "\n")
    print(f"\ntotal findings: {len(all_findings)}")
    print(f"by category   : {dict(totals)}")
    print(f"written       : {args.out}")
    control = totals.get("control", 0)
    if control:
        print(f"\nPRECISION FAILURE: {control} finding(s) in non-agent control repos", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
